### ISSUE TITLE
最新版本会导致用户崩溃

### ISSUE THREAD

**Issue by itzhaokun** [xuezj/CardBannerDemo#9]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.view.View.getTag(int)' on a null object reference
    at com.xuezj.cardbanner.view.CardView.getCurrentItem(CardView.java:160)
    at com.xuezj.cardbanner.CardBanner$2.run(CardBanner.java:195)
    at com.xuezj.cardbanner.i$c.run(WeakHandler.java:205)
    at android.os.Handler.handleCallback(Handler.java:809)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:166)
    at android.app.ActivityThread.main(ActivityThread.java:7555)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)

**Comment by Ium-Lab** [comment]
确实有这个问题，已经停止更新了吧
